TFIDF:
  max_features: 15000
  ngram_range: [1, 3]

training:
  test_size: 0.2
  random_state: 42


XGBoost:
  n_estimators: 800
  learning_rate: 0.05
  max_depth: 8
  subsample: 0.8
  colsample_bytree: 0.8
  random_state: 42
  tree_method: "hist"
  eval_metric: "mlogloss"
  early_stopping_rounds: 30