artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/gowtham-dd/Datasets/raw/main/nvd_combined_2010_2025.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["nvd_combined_2010_2025.csv"]
  REQUIRED_COLUMNS: 
    - "CVE_ID"
    - "Description" 
    - "CWE"
    - "CVSS_Score"
    - "Severity"


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/nvd_combined_2010_2025.csv
  train_file: artifacts/data_transformation/train.csv
  test_file: artifacts/data_transformation/test.csv
  label_encoder_file: artifacts/data_transformation/label_encoder.pkl
  tfidf_vectorizer_file: artifacts/data_transformation/tfidf_vectorizer.pkl



model_trainer:
  root_dir: artifacts/model_training
  model_dir: artifacts/model_training/model
  trained_model_path: artifacts/model_training/xgb_severity_model.pkl


model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_training/xgb_severity_model.pkl
  label_encoder_path: artifacts/data_transformation/label_encoder.pkl
  tfidf_vectorizer_path: artifacts/data_transformation/tfidf_vectorizer.pkl
  metric_file_name: artifacts/model_evaluation/metrics.csv